### PR TITLE
Feat/refactor

### PR DESCRIPTION
**Pull request by buraksekili**
This PR
- adds unit tests using the `jest` package,
- refactors code structure,
- adds a logic to prevent showing the `Tyk successfully installed` popup message every time VsCode is opened. So, if the extension is installed previously, this message won't be shown.
- adds a workflow to run unit tests

### CODE REVIEW

**Comment by letzya** [comment]
Why do we need to combine duplicates? Doesn't vscode handle that?

**Comment by buraksekili** [comment]
> Why do we need to combine duplicates? Doesn't vscode handle that?

VSCode does not handle this situation. Therefore, users might end up with duplicated entries containing similar information. For example, consider such json.schema field
```json
[
    {
        "fileMatch": [
            "apidef.*.json"
        ],
        "url": "<url>",
        "addedBy": "tyk"
    },
    {
        "fileMatch": [
            "temp.*.json"
        ],
        "url": "<url>",
        "addedBy": "tyk"
    }
]
```

Although these two entries use the same `url` field, there are two separate entries for the same `url`. 

To simply such entries, I combined duplicate entries. So, the above schema can be reduced into:
```json
[
    {
        "fileMatch": [
            "apidef.*.json",
            "temp.*.json"
        ],
        "url": "<url>",
        "addedBy": "tyk"
    }
]
```

 but if you think that we do not need to handle such situations, I can remove that 😄

**Comment by letzya** [comment]
do you know (or can you check) what is vscode behaviour if we don't use this logic?

**Comment by letzya** [comment]
I just tested it and it's working fine without any added logic so I think we are safe to close this PR for now :)

**Pull request closed without merging**
